language: php

sudo: required

services:
  - docker

php:
  - 7.1
  - 7.2

before_install:
  - cd tests
  - docker-compose up -d
  - cd ..
  - chmod +x ./tests/install-sqlsrv.sh
  - ./tests/install-sqlsrv.sh

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml

jobs:
  include:
    # PHP Nightly builds does not support SQLServer yet
    - stage: Nightly
      php: nightly
      before_install:
        - cd tests
        - docker-compose up -d
        - cd ..
      script:
        - vendor/bin/phpunit tests/Database/SQLite
        - vendor/bin/phpunit tests/Database/MySQL
        - vendor/bin/phpunit tests/Database/Postgres

    # Testing various PostgresSQL version
    - stage: Postgres
      php: 7.1
      addons:
         postgresql: "9.2"
      env:
        - "DB=postgres"
      before_install:
        - psql -c 'create database spiral;' -U postgres
      script:
        - vendor/bin/phpunit tests/Database/Postgres