language: php

sudo: required

services:
  - docker

php:
  - 7.1
  - 7.2

before_install:
  - cd tests
  - docker-compose up -d
  - cd ..

install:
  - composer install --no-interaction --prefer-source
  - chmod +x ./tests/install-sqlsrv.sh
  - ./tests/install-sqlsrv.sh

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml